name: Build and Scan Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, centos, rhel, fedora]
        version: [latest]  # Add specific versions if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/docker-rvm:${{ matrix.os }}-${{ matrix.version }} \
            --build-arg BASE_IMAGE=${{ matrix.os }}:${{ matrix.version }} .

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/docker-rvm:${{ matrix.os }}-${{ matrix.version }}'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'

      # - name: Push Docker Image
      #   if: success()
      #   run: |
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-rvm:${{ matrix.os }}-${{ matrix.version }}
